repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/checkmake/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
      - id: mypy
        additional_dependencies:
          # add stubs the project needs
          - types-requests
          - types-setuptools
      - id: mypy
        alias: mypy-json-output
        name: mypy (json output)
        args:
          [
            "--output",
            "json",
            "--hide-error-context",
            "--show-column-numbers",
            "--show-absolute-path",
            "--no-pretty",
            "--ignore-missing-imports",
            "--scripts-are-modules",
          ]
        additional_dependencies:
          # add stubs the project needs
          - types-requests
          - types-setuptools
        stages: [manual]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
      - id: ruff-check
        alias: ruff-check-rdjson
        args: ["--fix", "-q", "--output-format=rdjson"]
        stages: [manual]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.9
    hooks:
      - id: actionlint
        name: actionlint
        files: ^\.github/workflows/.*\.(yml|yaml)$
        args: ["-shellcheck", "shellcheck -S error"]
      - id: actionlint
        alias: actionlint-oneline
        name: actionlint (one line per one error)
        files: ^\.github/workflows/.*\.(yml|yaml)$
        args: ["-oneline", "-shellcheck", "shellcheck -S error"]
        stages: [manual]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.19.1
    hooks:
      - id: markdownlint-cli2
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        args: ["-x"]
      - id: shellcheck
        alias: shellcheck-diff-output
        name: shellcheck (diff output)
        entry: shellcheck
        language: system
        types: [shell]
        args: ["-f", "diff", "-x"]
        stages: [manual]
      - id: shellcheck
        alias: shellcheck-json-output
        name: shellcheck (json output)
        entry: shellcheck
        language: system
        types: [shell]
        args: ["-f", "json", "-x"]
        stages: [manual]
      - id: prettier-yaml
        name: prettier-yaml
        entry: prettier
        language: node
        additional_dependencies: ["prettier@3.7.4"]
        files: \.(yml|yaml)$
        args: ["--write"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
      - id: yamllint
        alias: yamllint-parsable
        name: "yamllint (parsable output)"
        args: ["--format", "parsable"]
        stages: [manual]
